version: 2.1
executors:
  python:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
commands:
  runtest:
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a virtual env
          command: |
            sudo pip install --upgrade pip
            pip install virtualenv
            virtualenv -p $(which python) ~/efs-utils-virtualenv
            source ~/efs-utils-virtualenv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run all tests
          command: |
            source ~/efs-utils-virtualenv/bin/activate
            make test
jobs:
  test:
    parameters:
      image:
        type: string
    executor:
      name: python
      image: << parameters.image >>
    steps:
      - runtest
workflows:
  workflow:
    jobs:
      - test:
          name: python38
          image: circleci/python:3.8.1
      - test:
          name: python37
          image: circleci/python:3.7.3
      - test:
          name: python36
          image: circleci/python:3.6.9
      - test:
          name: python35
          image: circleci/python:3.5.9
      - test:
          name: python34
          image: circleci/python:3.4.9
      - test:
          name: python27
          image: circleci/python:2.7.13